version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "@astrojs/check"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      linters:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "prettier*"
          - "markdownlint*"
          - "typescript-eslint"
          - "@commitlint/*"
          - "husky"
          - "lint-staged"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
